### ISSUE TITLE
Broken indention for scss files

### ISSUE THREAD

**Issue by GitRon** [rtts/djhtml#81] opened 2023-02-23 07:16 UTC
Hi @JaapJoris 

I have a scss file with multiple declarations beneith each other:

````scss
.icon-x-alarm:before { content: '\e800'; } /* '' */
.icon-x-align-center:before { content: '\e801'; } /* '' */
.icon-x-align-justify:before { content: '\e802'; } /* '' */
.icon-x-align-left:before { content: '\e803'; } /* '' */
.icon-x-align-right:before { content: '\e804'; } /* '' */
.icon-x-anchor:before { content: '\e805'; } /* '' */
````

What the linter does is this:

![grafik](https://user-images.githubusercontent.com/3176075/220841561-6e94f7e3-b3e1-41e1-9338-c02471fd3e60.png)

But that's the only bug I found so far 💪 

Best from Cologne
Ronny

**Comment by JaapJoris** [comment] 2023-02-23 08:54
Hi Ronny, and thank you for reporting this. This bug is actually worse than it seems: string detection in CSS mode is done "greedily", so that the following:

```css
.icon1:before { content:'foo'} .icon2:before { content:'bar'}
```

incorrectly leads to the substring `'foo'} .icon2:before { content:'bar'` being detected as an entire string (because it is technically the largest substring surrounded by quotes).

This was already fixed for DjJS mode, and I'll now also fix it for DjCSS mode and create a new release. Thanks again for noticing this so quickly!

**Comment by GitRon** [comment] 2023-02-23 08:55
Thx for fixing it that quickly! When will you release the bugfix?

**Comment by GitRon** [comment] 2023-02-23 09:01
It works 💪

**Comment by DmytroLitvinov** [comment] 2023-02-27 10:31
I am using `main` branch in pre-commit and we are having also strangle indentation in scss files.

Initial scss code:
```
$line-height:           1.5 !default; // calculating line-height: round($font-size * 1.5)
$line-space:            10px !default;
```

And how it indented:
```
$line-height:           1.5 !default; // calculating line-height: round($font-size * 1.5)
                                                                  $line-space:            10px !default;
```

Another one:
```
  // START: Quick dirty fix for Boostrap alert
  .alert {
    position: relative;
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 0 solid transparent;
    border-radius: 0;
```

And result:
```
  // START: Quick dirty fix for Boostrap alert
            .alert {
    position: relative;
    padding: 0.75rem 1.25rem;
    margin-bottom: 1rem;
    border: 0 solid transparent;
    border-radius: 0;
```

Seems like the issue somewhere with comments

**Comment by DmytroLitvinov** [comment] 2023-02-27 10:33
Adn this one is also strange:
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/16066485/221540394-b7d19f27-37de-4ef9-827b-f483152fe1bd.png">

**Comment by DmytroLitvinov** [comment] 2023-02-27 10:39
here is more information how it affects.

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/16066485/221541406-0ac75a2c-7fa6-4f8a-8836-fd08ba6aabe9.png">
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/16066485/221541513-42fe4395-9872-488d-94ad-7e8f0c803c0b.png">
<img width="979" alt="image" src="https://user-images.githubusercontent.com/16066485/221541655-bdd2a34d-ecee-4ada-ad56-175192117166.png">
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/16066485/221541702-c07fa5ea-0e0a-4675-920c-2f713563323a.png">

**Comment by JaapJoris** [comment] 2023-02-27 17:06
Thanks for reporting these bugs. They all stem from the problem that my understanding of SCSS and, by extension, DjCSS's understanding is limited. The first bug you reported is caused by DjCSS not being aware that `//` starts a comment. The following:

```css
div {
    foo: bar; // comment: ignore
    font-weight: bold;
}
```

therefore gets indented as this:

```css
div {
    foo: bar; // comment: ignore
                          font-weight: bold;
}
```

Because DjCSS thinks that `comment:` is a CSS attribute without the trailing `;`. Adding one fixes it:

```css
div {
    foo: bar; // comment: ignore;
    font-weight: bold;
}
```

The second problem is that DjCSS treats text between `(` and `)` no different than ordinary attribute/value pairs in CSS. Note that the following:

```css
@font-face {
    src: url('Arial.woff2') format('woff2'),
         url('Arial.woff') format('woff');
}
```

is consistent with the following, from DjCSS's perspective:

```css
@include button-outline-variant(
    $color: $white,
            $hover-background;
)
```

This is a harder problem, but I think it can be fixed by special-casing stuff between `(` and `)`.

Are there any further SCSS peculiarities that I'm not yet aware of?

**Comment by DmytroLitvinov** [comment] 2023-02-27 19:29
Thank you for explaining @JaapJoris .

Here are more examples. Can you check whatever is related to the issue?

1. Not sure that closing parenthesis
<img width="915" alt="image" src="https://user-images.githubusercontent.com/16066485/221662373-94442149-0bac-4b60-a5cf-58af0dac0bf4.png">

2. I would expect it under `screen`.
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/16066485/221662570-8e8da408-0c0c-4767-b10f-c60367ca44f3.png">

3. Maybe this one would be interested also
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/16066485/221663613-85baed42-c4e2-4d55-9073-f74be57b6a6c.png">

**Comment by oselz** [comment] 2023-02-28 20:14
Here is another simple example I just hit:
```scss
$grid-breakpoints: (
    xs: 0,
    sm: 576px,
    md: 768px,
    lg: 992px,
    xl: 1200px
) !default;
```
```scss
$grid-breakpoints: (
                     xs: 0,
      sm: 576px,
      md: 768px,
      lg: 992px,
      xl: 1200px
    ) !default;
```

**Closed as completed** 2023-03-07 21:26 UTC

**Comment by JaapJoris** [comment] 2023-03-07 21:38
I believe all these problems are now fixed in [the latest release](https://github.com/rtts/djhtml/releases/tag/3.0.4) :partying_face: 

If you find any further problems, please [open a new issue](https://github.com/rtts/djhtml/issues/new) with examples of both the expected and actual output. And a special request: no screenshots please, it was really annoying having to type out the information from a picture instead of being able to copy the text :pray:

**Comment by GitRon** [comment] 2023-03-08 08:07
Hi @JaapJoris 

I updated to the latest version and now get this odd behaviour 😅 

![grafik](https://user-images.githubusercontent.com/3176075/223656444-e9f531fd-2981-485b-98c4-d352e9dd338e.png)

Best from Cologne  
Ronny

**Comment by GitRon** [comment] 2023-03-08 08:07
Ooops, sorry, will create a new issue.
