### ISSUE TITLE
Not working with django-template-partials

### ISSUE THREAD

**Issue by Thutmose3** [rtts/djhtml#111] opened 2024-02-18 12:36 UTC
I'm using django-template-partials (https://github.com/carltongibson/django-template-partials)
Its a nice library to create small components to be reused in templates.

This library has 2 template tags and it formats them wrong:

```
<div class="grid grid-cols-12 gap-4">
    {% partial product_dimensions %}
        <div class="sm:col-span-5">
```

It should be like this:
```
<div class="grid grid-cols-12 gap-4">
    {% partial product_dimensions %}
    <div class="sm:col-span-5">
```

This is the other template tag that is wrongly formatted:
```
<div class="w-full">
    {% startpartial product_images %}
    {% for image in images %}
        {{ image }}
    {% endfor %}
    {% endpartial %}
</div>
```

It should be like this:
```
<div class="w-full">
    {% startpartial product_images %}
        {% for image in images %}
            {{ image }}
        {% endfor %}
    {% endpartial %}
</div>
```

**Comment by JaapJoris** [comment] 2024-05-07 14:13
This bug is caused by the mechanism that DjHTML uses to determine whether `{% foo %}` is a block tag: it looks ahead to see whether an `{% endfoo %}` exists. If it does, then it determines that everything between `{% foo %}` and `{% endfoo %}` should be indented.

In your case, when both `{% partial %}` and `{% endpartial %}` exist in the same file, it determines that the content after `{% partial %}` should be indented. Likewise, it determines that the content after `{% startpartial %}` should not be indented, because no `{% endstartpartial %}` exists. Both problems are caused by the unconventional naming of block tags by https://github.com/carltongibson/django-template-partials

I will ponder for a while whether to fix or wontfix this issue, and then get back to you.

**Comment by JaapJoris** [comment] 2024-05-09 20:05
Good news! This issue was fixed upstream in https://github.com/carltongibson/django-template-partials/issues/12 by replacing the `{# startpartial #}` and `{# endpartial #}` tags with the new `{# partialdef %}` and `{% endpartialdef %}` tags:

```
<div class="w-full">
    {% partialdef product_images %}
        {% for image in images %}
            {{ image }}
        {% endfor %}
    {% endpartialdef %}
</div>
```

**Closed as completed by JaapJoris** 2024-05-09 20:05 UTC
Labels: fixed-upstream
