### ISSUE TITLE
html comment lines not indented

### ISSUE THREAD

**Issue by minusf** [rtts/djhtml#98] opened 2023-05-08 08:48 UTC
it seems that html comment lines are not indented:

```
<p>
    <!-- some comment -->
</p>
```

```
-   repo: https://github.com/rtts/djhtml
    rev: '3.0.6'
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2
```

**Comment by JaapJoris** [comment] 2023-05-08 16:49
Hi there, thanks for taking the time to contribute! In general, I've found it impossible to correctly indent comments in all situations, so that's why comments are currently not indented at all. The [release notes](https://github.com/rtts/djhtml/releases/tag/3.0.0) give this example:

```
<div>
    <p>
        {# ╔══════════════════════════╗
   ║ Carefully laid out table ║
   ╚══════════════════════════╝ #}
    </p>
</div>
```

I'll hope you forgive me for closing this issue, as not indenting comments is the intended behavior.

**Closed as completed by JaapJoris** 2023-05-08 16:49 UTC

**Comment by minusf** [comment] 2023-05-08 18:43
i have missed in the readme that comments are ignored, my mistake.

(on the other hand i dont do much ascii art on multiline comments, so it would have been nice if one line comments were handled...)
